spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
          - localhost:9092
      bindings:
        input:
         binder: kafka
         destination: vivek
         content-type: text/plain
         group: input-group-1
        output:
          binder: kafka
          destination: vivek
          group: output-group-1
          content-type: application/json
server:
  port: 8083
      

